### ISSUE TITLE
Authentication and Registration 

### ISSUE THREAD

**Issue by jabrayare** [IOS-CodePath-Group31/Unit5GroupMileStone#2]
- Registration Screen
        - Users can create an account.
- Login Screen
      - Login.
- Logout

**Comment by mimiog** [comment]
I've created parse and the registration screen. Users should be able to create an account. I also created the login screen, I have not yet configured login authentication yet. I have not created logout and might not be able to do so until we have a home screen/profile screen.

**Comment by mimiog** [comment]
Completed all requirements.
